// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpoaosjdbxbntbneoxha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwb2Fvc2pkYnhibnRibmVveGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzM4NDcsImV4cCI6MjA2MDA0OTg0N30.ifpHvhT9xgP8-iwN9eP7npF4akoRMbGUr7sXtxzk2Rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);